export const VIEW_COURSE_CATEGORY = 'VIEW_COURSE_CATEGORY';
export const VIEW_COURSE_CATEGORY_SUCCESS = 'VIEW_COURSE_CATEGORY_SUCCESS';
export const GET_ADVERTISEMENT = 'GET_ADVERTISEMENT';
export const GET_ADVERTISEMENT_SUCCESS = 'GET_ADVERTISEMENT_SUCCESS';
export const REPORT_ACTION_RECENT = 'REPORT_ACTION_RECENT';
export const REPORT_ACTION_RECENT_SUCCESS = 'REPORT_ACTION_RECENT_SUCCESS';
export const REPORT_COUNT_SUCCESS = 'REPORT_COUNT_SUCCESS';
export const REPORT_COUNT = 'REPORT_COUNT';
export const EXPORT_EXAM_SCHEDULE = 'EXPORT_EXAM_SCHEDULE';
export const REGISTER_EXAM_SCHEDULE = 'REGISTER_EXAM_SCHEDULE';
export const GET_ALL_ROOMS_BY_STATUS = 'GET_ALL_ROOMS_BY_STATUS';
export const GET_ALL_ROOMS_BY_STATUS_SUCCESS = 'GET_ALL_ROOMS_BY_STATUS_SUCCESS';
export const GET_MEMBER_BY_TYPE_AND_STATUS = 'GET_MEMBER_BY_TYPE_AND_STATUS';
export const GET_MEMBER_BY_TYPE_AND_STATUS_SUCCESS = 'GET_MEMBER_BY_TYPE_AND_STATUS_SUCCESS';
export const EXPORT_MEMBER = 'EXPORT_MEMBER';
export const IMPORT_UPDATE_SCORE = 'IMPORT_UPDATE_SCORE';
export const UPDATE_SCORE_BY_EXCEL = 'UPDATE_SCORE_BY_EXCEL';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const GET_ALL_ROOMS = 'GET_ALL_ROOMS';
export const GET_ALL_ROOMS_SUCCESS = 'GET_ALL_ROOMS_SUCCESS';
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS';
export const GET_ALL_TEACHERS_SUCCESS = 'GET_ALL_TEACHERS_SUCCESS';
export const GENERATE_SCHEDULE = 'GENERATE_SCHEDULE';
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS';
export const GET_SCHEDULE = 'GET_SCHEDULE';
export const GET_CLASS = 'GET_CLASS';
export const ADD_CLASS = 'ADD_CLASS';
export const UPDATE_CLASS = 'UPDATE_CLASS';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const GET_ALL_COURSE_SUCCESS = 'GET_ALL_COURSE_SUCCESS';
export const GET_ALL_COURSE = 'GET_ALL_COURSE';
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const ADD_DOCUMENT  = 'ADD_DOCUMENT';
export const UPDATE_DOCUMENT  = 'UPDATE_DOCUMENT';
export const DELETE_DOCUMENT  = 'DELETE_DOCUMENT';

// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU';
export const WINDOW_WIDTH = 'WINDOW-WIDTH';
export const SWITCH_LANGUAGE = 'SWITCH-LANGUAGE';

//Contact Module const
export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const REQUEST_FORGET_PASSWORD = 'REQUEST_FORGET_PASSWORD';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';

//Auth const
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const INIT_URL = 'INIT_URL';
export const ON_HIDE_LOADER_TABLE = 'ON_HIDE_LOADER_TABLE';
export const CLEAR_ITEMS = 'CLEAR_ITEMS';

//get list
export const GET_MEMBER = 'GET_MEMBER';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';
export const ADD_MEMBER = 'ADD_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_UPDATE_MEMBER = 'SHOW_UPDATE_MEMBER';
export const HIDE_UPDATE_MEMBER = 'HIDE_UPDATE_MEMBER';
export const HIDE_CHANGE_PASSWORD = 'HIDE_CHANGE_PASSWORD';
export const SHOW_CHANGE_PASSWORD = 'SHOW_CHANGE_PASSWORD';
export const SELECT_INDEX = 'SELECT_INDEX';
export const SET_MEMBER = 'SET_MEMBER';
export const GET_CURRENT_MEMBER= 'GET_CURRENT_MEMBER';
export const UPDATE_CURRENT_MEMBER = 'UPDATE_CURRENT_MEMBER';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const GET_COURSE_CATEGORY = 'GET_COURSE_CATEGORY';
export const ADD_COURSE_CATEGORY = 'ADD_COURSE_CATEGORY';
export const UPDATE_COURSE_CATEGORY = 'UPDATE_COURSE_CATEGORY';
export const DELETE_COURSE_CATEGORY = 'DELETE_COURSE_CATEGORY';

export const GET_COURSE = 'GET_COURSE';
export const ADD_COURSE = 'ADD_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const GET_ALL_COURSE_CATEGORY = 'GET_ALL_COURSE_CATEGORY';
export const GET_ALL_COURSE_CATEGORY_SUCCESS = 'GET_ALL_COURSE_CATEGORY_SUCCESS';

export const GET_SHIFT = 'GET_SHIFT';
export const ADD_SHIFT = 'ADD_SHIFT';
export const UPDATE_SHIFT = 'UPDATE_SHIFT';
export const DELETE_SHIFT = 'DELETE_SHIFT';

export const GET_ALL_SHIFT = 'GET_ALL_SHIFT';
export const GET_ALL_SHIFT_SUCCESS = 'GET_ALL_SHIFT_SUCCESS';

export const GET_ROOM = 'GET_ROOM';
export const ADD_ROOM = 'ADD_ROOM';
export const UPDATE_ROOM = 'UPDATE_ROOM';
export const DELETE_ROOM = 'DELETE_ROOM';

export const GET_EXAM_SCHEDULE = 'GET_EXAM_SCHEDULE';
export const ADD_EXAM_SCHEDULE = 'ADD_EXAM_SCHEDULE';
export const UPDATE_EXAM_SCHEDULE = 'UPDATE_EXAM_SCHEDULE';
export const DELETE_EXAM_SCHEDULE = 'DELETE_EXAM_SCHEDULE';

export const GET_ALL_COURSE_CATEGORY_ADD = 'GET_ALL_COURSE_CATEGORY_ADD';
export const GET_ALL_COURSE_CATEGORY_ADD_SUCCESS = 'GET_ALL_COURSE_CATEGORY_ADD_SUCCESS';

export const GET_ALL_COURSE_ADD = 'GET_ALL_COURSE_ADD';
export const GET_ALL_COURSE_ADD_SUCCESS = 'GET_ALL_COURSE_ADD_SUCCESS';
